import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import CardComponent from '../src/Component/Card/Index'
import BASE_URL from '.././src/Constant/base_url'
import { useDispatch } from 'react-redux'
import { addUser } from '../src/redux/Slice/User'
import { wrapper } from '../src/redux/store'


const Home: NextPage = ({ data }: any) => {
  const user = useSelector((state: { user: any }) => state.user)
  console.log(user)
  return (
    <div className='  flex items-start justify-center h-screen bg-slate-900 '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className=' text-white'>{user.name}</p>
      <CardComponent />
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(store => (ctx: any): any => {
  store.dispatch(addUser('was set in other page'));
  return {
    props: {}
  }
});


export default Home
